### ISSUE TITLE
add label box / label module

### ISSUE THREAD

**Issue by zoepage** [webcompat/design#16]

**Comment by magsout** [comment]
@zoepage could you give me more informations about this issue?

TBH, I don't really understand :(

**Comment by zoepage** [comment]
So, as we are building the style guide and prepare the refactor, we need a module (just HTML + CSS) for the label box.

OLD:
<img width="382" alt="screen shot 2017-11-17 at 4 00 12 pm" src="https://user-images.githubusercontent.com/562354/32953401-5c64431e-cbb0-11e7-9e78-1570c793a63a.png">
<img width="715" alt="screen shot 2017-11-17 at 4 00 20 pm" src="https://user-images.githubusercontent.com/562354/32953402-5c7d1902-cbb0-11e7-8094-efd132eefce0.png">

The spot in the grid is already there and should be merged into master in about 1-2 hours.

The plan is to get it in as it is with the new grid / CSS and semantics and go from there, but no js-classes / functionality. Just the css and semantics for the style guide.

So what we would need is:

- create a new branch `issues/16` 
- create a new file for the label-box module -> `label-box.css` in the css folder
- take the grid class for `x1-fix` (check http://webcompat.github.io/design/ - "Module: Grid - 2:1 / 1:2" for documentation) and put it in there. 
- During the refactor we'll then take that HTML / CSS and apply the "old" js-classes as well as functionality into the new site. 

No need to work on anything outside the grid box... If you want to take a look about the state atm, checkout `issues/15` and search for `LABEL BOX`.

Does this explanation work for you? 

The only thing that is changing is, the labels have a border now and not a background as they used to have. See "Module: Issues List" at http://webcompat.github.io/design/
https://github.com/webcompat/webcompat.com/issues/1522#issuecomment-297246594

**Comment by zoepage** [comment]
Sorry, take `master` as `issues/15` got merged :)
