### ISSUE TITLE
add linter

### ISSUE THREAD

**Issue by zoepage** [webcompat/design#4]
- [x] add prettier
- [x] add rules same as in webcompat.com
- [x] add task to run linter

**Comment by magsout** [comment]
@zoepage may I work on this issue ?

**Comment by zoepage** [comment]
That would be great @magsout  :)

**Comment by magsout** [comment]
@zoepage just fewt questions.

- should we adding a CI ? like travis or circleci ?
- using stylelint is enought, or adding prettier is something that you want ?
- do we keep docs folder or renamed in src or lib ? (just because I use to see src or lib, but it's not very important ;) )

**Comment by zoepage** [comment]
The code for the style guide will be moved to the main repository after the sprint. The purpose of the linter is to help us keep up the code quality for the sprint... So no need for massive work. Basic setup is already super helpful!

> should we adding a CI ? like travis or circleci ?

npm script should be fine for now, so we can run `npm lint` manually. If you want to add a pre-commit hook, I'd love that! :)))

> using stylelint is enought, or adding prettier is something that you want ?

It will be using the same linter than webcompat.com later. So whatever you decide and makes more sense. :)

> do we keep docs folder or renamed in src or lib ?

The style guide will be auto-generated later on. So, this does not matter atm :)

**Comment by zoepage** [comment]
So cool @magsout :)))

Could we exclude 2 files?
reset.css as well as a11y.css?

Did we set up the pre-commit hook yet?

**Comment by magsout** [comment]
@zoepage 
>Could we exclude 2 files?
reset.css as well as a11y.css?

yes, ok, done

>Did we set up the pre-commit hook yet?

there https://github.com/webcompat/design/pull/47/commits/91d12e86d0e16b43b0227399d4d7fba8be961862#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R26 ?

**Comment by madeleine-neumann** [comment]
<img width="1184" alt="bildschirmfoto 2017-11-15 um 16 38 58" src="https://user-images.githubusercontent.com/508548/32844777-8381a3ee-ca23-11e7-8667-0b3250b8afa4.png">

VSCode just give me the hint, that the rule: selector-no-id is undefined. It seems like, that the stylelint selector-no-* rules are deprecated.

Source: https://github.com/stylelint/stylelint/issues/2528\
@magsout can you take a look please? :)

**Comment by magsout** [comment]
@madeleine-neumann oh yes, thanks for the ping.

**Comment by magsout** [comment]
@madeleine-neumann have you got the way to choose the version you use in VSCode ?

**Comment by madeleine-neumann** [comment]
vscode-stylelint: 0.30.0 (but no Idea wich version of the original stylelint will be used)

**Comment by madeleine-neumann** [comment]
@magsout Hi there again, the following rules in the repo aren't working:
```
      "selector-no-id": true,
        "selector-no-attribute": true,
        "function-url-data-uris": "never",
        "selector-no-universal": true,
        "selector-no-type": true,
```

Maybe it helps you :)

**Comment by madeleine-neumann** [comment]
@magsout Found one more problem where 2 rules are fighting against each other.
If a Selector is a multiline selector, it expects at first a new line after it and also a single space after the colon. When I add the space after the colon, I get the error, that there is an unexpected whitespace :)
<img width="387" alt="bildschirmfoto 2017-11-18 um 12 00 43" src="https://user-images.githubusercontent.com/508548/32979585-225f0f5c-cc58-11e7-8f93-ceba60d77866.png">

<img width="882" alt="bildschirmfoto 2017-11-18 um 11 59 12" src="https://user-images.githubusercontent.com/508548/32979583-157798a4-cc58-11e7-8359-432269e7cdaa.png">
