### ISSUE TITLE
Add classes for form validation

### ISSUE THREAD

**Issue by zoepage** [webcompat/design#57]
We need to add the functionality (classes, ids, names for inputs etc) to prep the form for the refactor, so the transfer is not so complicated.

**Comment by skyschub** [comment]
Closing this as a WONTFIX. As it turns out, the template is rather complex and we have to work on it anyway, so we don't actually gain anything in regards to ease of porting to the new layout. Let's just adopt the HTML when we're actually moving stuff, not ahead of time.
