### ISSUE TITLE
Create favicons

### ISSUE THREAD

**Issue by zoepage** [webcompat/design#62]
I've uploaded all logo files.
https://github.com/webcompat/design/tree/master/archive/logos

We need to generate favicons from "just the bulb". Probably the line thickness needs to be increased, too.

Which ones we need, you'll find here: https://github.com/webcompat/webcompat.com/issues/1338#issuecomment-280159994

**Comment by lewiscowper** [comment]
[favicon.zip](https://github.com/webcompat/design/files/1484707/favicon.zip)

Want to check these favicons out @zoepage? All looks good from my side, but I'm no designer.

**Comment by lewiscowper** [comment]
[favicon.zip](https://github.com/webcompat/design/files/1484707/favicon.zip)

Want to check these favicons out @zoepage? All looks good from my side, but I'm no designer.

**Comment by zoepage** [comment]
They look great @lewiscowper!!! :) 
They are not in a branch yet, right?

Would you mind to add them to a branch with this issue number: https://github.com/webcompat/webcompat.com/issues/1338, as this is your commit and you deserve the credit for it? :)

**Comment by zoepage** [comment]
https://github.com/webcompat/webcompat.com/issues/1894 would be even better :)

**Comment by lewiscowper** [comment]
👍

**Comment by zoepage** [comment]
done in webcompat.com/1894
