### ISSUE TITLE
Fix CSS specificity

### ISSUE THREAD

**Issue by kotzendekrabbe** [webcompat/design#72]
We want to fix the CSS specificity of some of the selectors
'.class.class .class' 

- [x] write down css specificty rules

- [x] make examples for better understanding

- [x] rewrite css selectors

**Comment by zoepage** [comment]
To fix following:
https://github.com/webcompat/design/blob/master/docs/css/labels.css#L1

**Comment by kotzendekrabbe** [comment]
to reduce specificity problems in the stylesheets we want to use the following rules.
there will be exceptions - but most the time we can use the rules everywhere.
if there are exceptions, it's important to comment them - so everyone understand why we need to break the rule at a place.

**rules** 
- css selectors don't need to be combined with more than three selectors as one single selector 
- don't use ids for styling (we only need them for functionality)
- avoid to use universal selector
- avoid to use !important, there are usecases for !important, but in 99.99% of the time you don't need it


**selector examples**
good:
.classname {}
.classname .classname1 {}
.classneme:pseudo-element {}

bad:
.classname.classname1 .classname2 {}
#idname . classname .classname1 {} 
.classname #idname {}

**Comment by kotzendekrabbe** [comment]
@madeleine-neumann let us talk about it before you start, the issue-list task from @zoepage is a little bit complicated :)

**Comment by zoepage** [comment]
this is done, correct? :)
